// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// DeviceLocation is an object representing the database table.
type DeviceLocation struct {
	Time      time.Time `db:"time,pk" `
	DeviceID  string    `db:"device_id,pk" `
	SpaceSlug string    `db:"space_slug" `
	Latitude  float64   `db:"latitude" `
	Longitude float64   `db:"longitude" `
	Accuracy  float64   `db:"accuracy" `
}

// DeviceLocationSlice is an alias for a slice of pointers to DeviceLocation.
// This should almost always be used instead of []*DeviceLocation.
type DeviceLocationSlice []*DeviceLocation

// DeviceLocations contains methods to work with the device_locations table
var DeviceLocations = psql.NewTablex[*DeviceLocation, DeviceLocationSlice, *DeviceLocationSetter]("", "device_locations", buildDeviceLocationColumns("device_locations"))

// DeviceLocationsQuery is a query on the device_locations table
type DeviceLocationsQuery = *psql.ViewQuery[*DeviceLocation, DeviceLocationSlice]

func buildDeviceLocationColumns(alias string) deviceLocationColumns {
	return deviceLocationColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"time", "device_id", "space_slug", "latitude", "longitude", "accuracy",
		).WithParent("device_locations"),
		tableAlias: alias,
		Time:       psql.Quote(alias, "time"),
		DeviceID:   psql.Quote(alias, "device_id"),
		SpaceSlug:  psql.Quote(alias, "space_slug"),
		Latitude:   psql.Quote(alias, "latitude"),
		Longitude:  psql.Quote(alias, "longitude"),
		Accuracy:   psql.Quote(alias, "accuracy"),
	}
}

type deviceLocationColumns struct {
	expr.ColumnsExpr
	tableAlias string
	Time       psql.Expression
	DeviceID   psql.Expression
	SpaceSlug  psql.Expression
	Latitude   psql.Expression
	Longitude  psql.Expression
	Accuracy   psql.Expression
}

func (c deviceLocationColumns) Alias() string {
	return c.tableAlias
}

func (deviceLocationColumns) AliasedAs(alias string) deviceLocationColumns {
	return buildDeviceLocationColumns(alias)
}

// DeviceLocationSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type DeviceLocationSetter struct {
	Time      omit.Val[time.Time] `db:"time,pk" `
	DeviceID  omit.Val[string]    `db:"device_id,pk" `
	SpaceSlug omit.Val[string]    `db:"space_slug" `
	Latitude  omit.Val[float64]   `db:"latitude" `
	Longitude omit.Val[float64]   `db:"longitude" `
	Accuracy  omit.Val[float64]   `db:"accuracy" `
}

func (s DeviceLocationSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.Time.IsValue() {
		vals = append(vals, "time")
	}
	if s.DeviceID.IsValue() {
		vals = append(vals, "device_id")
	}
	if s.SpaceSlug.IsValue() {
		vals = append(vals, "space_slug")
	}
	if s.Latitude.IsValue() {
		vals = append(vals, "latitude")
	}
	if s.Longitude.IsValue() {
		vals = append(vals, "longitude")
	}
	if s.Accuracy.IsValue() {
		vals = append(vals, "accuracy")
	}
	return vals
}

func (s DeviceLocationSetter) Overwrite(t *DeviceLocation) {
	if s.Time.IsValue() {
		t.Time = s.Time.MustGet()
	}
	if s.DeviceID.IsValue() {
		t.DeviceID = s.DeviceID.MustGet()
	}
	if s.SpaceSlug.IsValue() {
		t.SpaceSlug = s.SpaceSlug.MustGet()
	}
	if s.Latitude.IsValue() {
		t.Latitude = s.Latitude.MustGet()
	}
	if s.Longitude.IsValue() {
		t.Longitude = s.Longitude.MustGet()
	}
	if s.Accuracy.IsValue() {
		t.Accuracy = s.Accuracy.MustGet()
	}
}

func (s *DeviceLocationSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return DeviceLocations.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.Time.IsValue() {
			vals[0] = psql.Arg(s.Time.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.DeviceID.IsValue() {
			vals[1] = psql.Arg(s.DeviceID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.SpaceSlug.IsValue() {
			vals[2] = psql.Arg(s.SpaceSlug.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Latitude.IsValue() {
			vals[3] = psql.Arg(s.Latitude.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Longitude.IsValue() {
			vals[4] = psql.Arg(s.Longitude.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Accuracy.IsValue() {
			vals[5] = psql.Arg(s.Accuracy.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s DeviceLocationSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s DeviceLocationSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.Time.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "time")...),
			psql.Arg(s.Time),
		}})
	}

	if s.DeviceID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "device_id")...),
			psql.Arg(s.DeviceID),
		}})
	}

	if s.SpaceSlug.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "space_slug")...),
			psql.Arg(s.SpaceSlug),
		}})
	}

	if s.Latitude.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "latitude")...),
			psql.Arg(s.Latitude),
		}})
	}

	if s.Longitude.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "longitude")...),
			psql.Arg(s.Longitude),
		}})
	}

	if s.Accuracy.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "accuracy")...),
			psql.Arg(s.Accuracy),
		}})
	}

	return exprs
}

// FindDeviceLocation retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindDeviceLocation(ctx context.Context, exec bob.Executor, TimePK time.Time, DeviceIDPK string, cols ...string) (*DeviceLocation, error) {
	if len(cols) == 0 {
		return DeviceLocations.Query(
			sm.Where(DeviceLocations.Columns.Time.EQ(psql.Arg(TimePK))),
			sm.Where(DeviceLocations.Columns.DeviceID.EQ(psql.Arg(DeviceIDPK))),
		).One(ctx, exec)
	}

	return DeviceLocations.Query(
		sm.Where(DeviceLocations.Columns.Time.EQ(psql.Arg(TimePK))),
		sm.Where(DeviceLocations.Columns.DeviceID.EQ(psql.Arg(DeviceIDPK))),
		sm.Columns(DeviceLocations.Columns.Only(cols...)),
	).One(ctx, exec)
}

// DeviceLocationExists checks the presence of a single record by primary key
func DeviceLocationExists(ctx context.Context, exec bob.Executor, TimePK time.Time, DeviceIDPK string) (bool, error) {
	return DeviceLocations.Query(
		sm.Where(DeviceLocations.Columns.Time.EQ(psql.Arg(TimePK))),
		sm.Where(DeviceLocations.Columns.DeviceID.EQ(psql.Arg(DeviceIDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after DeviceLocation is retrieved from the database
func (o *DeviceLocation) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = DeviceLocations.AfterSelectHooks.RunHooks(ctx, exec, DeviceLocationSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = DeviceLocations.AfterInsertHooks.RunHooks(ctx, exec, DeviceLocationSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = DeviceLocations.AfterUpdateHooks.RunHooks(ctx, exec, DeviceLocationSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = DeviceLocations.AfterDeleteHooks.RunHooks(ctx, exec, DeviceLocationSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the DeviceLocation
func (o *DeviceLocation) primaryKeyVals() bob.Expression {
	return psql.ArgGroup(
		o.Time,
		o.DeviceID,
	)
}

func (o *DeviceLocation) pkEQ() dialect.Expression {
	return psql.Group(psql.Quote("device_locations", "time"), psql.Quote("device_locations", "device_id")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the DeviceLocation
func (o *DeviceLocation) Update(ctx context.Context, exec bob.Executor, s *DeviceLocationSetter) error {
	v, err := DeviceLocations.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single DeviceLocation record with an executor
func (o *DeviceLocation) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := DeviceLocations.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the DeviceLocation using the executor
func (o *DeviceLocation) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := DeviceLocations.Query(
		sm.Where(DeviceLocations.Columns.Time.EQ(psql.Arg(o.Time))),
		sm.Where(DeviceLocations.Columns.DeviceID.EQ(psql.Arg(o.DeviceID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after DeviceLocationSlice is retrieved from the database
func (o DeviceLocationSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = DeviceLocations.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = DeviceLocations.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = DeviceLocations.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = DeviceLocations.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o DeviceLocationSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Group(psql.Quote("device_locations", "time"), psql.Quote("device_locations", "device_id")).In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o DeviceLocationSlice) copyMatchingRows(from ...*DeviceLocation) {
	for i, old := range o {
		for _, new := range from {
			if new.Time.Equal(old.Time) {
				continue
			}
			if new.DeviceID != old.DeviceID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o DeviceLocationSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return DeviceLocations.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *DeviceLocation:
				o.copyMatchingRows(retrieved)
			case []*DeviceLocation:
				o.copyMatchingRows(retrieved...)
			case DeviceLocationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a DeviceLocation or a slice of DeviceLocation
				// then run the AfterUpdateHooks on the slice
				_, err = DeviceLocations.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o DeviceLocationSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return DeviceLocations.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *DeviceLocation:
				o.copyMatchingRows(retrieved)
			case []*DeviceLocation:
				o.copyMatchingRows(retrieved...)
			case DeviceLocationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a DeviceLocation or a slice of DeviceLocation
				// then run the AfterDeleteHooks on the slice
				_, err = DeviceLocations.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o DeviceLocationSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals DeviceLocationSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := DeviceLocations.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o DeviceLocationSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := DeviceLocations.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o DeviceLocationSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := DeviceLocations.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type deviceLocationWhere[Q psql.Filterable] struct {
	Time      psql.WhereMod[Q, time.Time]
	DeviceID  psql.WhereMod[Q, string]
	SpaceSlug psql.WhereMod[Q, string]
	Latitude  psql.WhereMod[Q, float64]
	Longitude psql.WhereMod[Q, float64]
	Accuracy  psql.WhereMod[Q, float64]
}

func (deviceLocationWhere[Q]) AliasedAs(alias string) deviceLocationWhere[Q] {
	return buildDeviceLocationWhere[Q](buildDeviceLocationColumns(alias))
}

func buildDeviceLocationWhere[Q psql.Filterable](cols deviceLocationColumns) deviceLocationWhere[Q] {
	return deviceLocationWhere[Q]{
		Time:      psql.Where[Q, time.Time](cols.Time),
		DeviceID:  psql.Where[Q, string](cols.DeviceID),
		SpaceSlug: psql.Where[Q, string](cols.SpaceSlug),
		Latitude:  psql.Where[Q, float64](cols.Latitude),
		Longitude: psql.Where[Q, float64](cols.Longitude),
		Accuracy:  psql.Where[Q, float64](cols.Accuracy),
	}
}
