// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var DeviceLocations = Table[
	deviceLocationColumns,
	deviceLocationIndexes,
	deviceLocationForeignKeys,
	deviceLocationUniques,
	deviceLocationChecks,
]{
	Schema: "",
	Name:   "device_locations",
	Columns: deviceLocationColumns{
		Time: column{
			Name:      "time",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DeviceID: column{
			Name:      "device_id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DeviceEui: column{
			Name:      "device_eui",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		OrganizationSlug: column{
			Name:      "organization_slug",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Latitude: column{
			Name:      "latitude",
			DBType:    "double precision",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Longitude: column{
			Name:      "longitude",
			DBType:    "double precision",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		AccuracyGateways: column{
			Name:      "accuracy_gateways",
			DBType:    "integer",
			Default:   "1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: deviceLocationIndexes{
		DeviceLocationsPK: index{
			Type: "btree",
			Name: "device_locations_pk",
			Columns: []indexColumn{
				{
					Name:         "\"time\"",
					Desc:         null.FromCond(false, true),
					IsExpression: true,
				},
				{
					Name:         "device_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		DeviceLocationsTimeIdx: index{
			Type: "btree",
			Name: "device_locations_time_idx",
			Columns: []indexColumn{
				{
					Name:         "\"time\"",
					Desc:         null.FromCond(true, true),
					IsExpression: true,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{true},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "device_locations_pk",
		Columns: []string{"time", "device_id"},
		Comment: "",
	},

	Comment: "",
}

type deviceLocationColumns struct {
	Time             column
	DeviceID         column
	DeviceEui        column
	OrganizationSlug column
	Latitude         column
	Longitude        column
	AccuracyGateways column
}

func (c deviceLocationColumns) AsSlice() []column {
	return []column{
		c.Time, c.DeviceID, c.DeviceEui, c.OrganizationSlug, c.Latitude, c.Longitude, c.AccuracyGateways,
	}
}

type deviceLocationIndexes struct {
	DeviceLocationsPK      index
	DeviceLocationsTimeIdx index
}

func (i deviceLocationIndexes) AsSlice() []index {
	return []index{
		i.DeviceLocationsPK, i.DeviceLocationsTimeIdx,
	}
}

type deviceLocationForeignKeys struct{}

func (f deviceLocationForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type deviceLocationUniques struct{}

func (u deviceLocationUniques) AsSlice() []constraint {
	return []constraint{}
}

type deviceLocationChecks struct{}

func (c deviceLocationChecks) AsSlice() []check {
	return []check{}
}
