// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var DeviceLocationErrors = &deviceLocationErrors{
	ErrUniqueDeviceLocationsPk: &UniqueConstraintError{
		schema:  "",
		table:   "device_locations",
		columns: []string{"time", "device_id"},
		s:       "device_locations_pk",
	},
}

type deviceLocationErrors struct {
	ErrUniqueDeviceLocationsPk *UniqueConstraintError
}
