// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/telemetry/v1/alerts": {
            "get": {
                "description": "Retrieve alerts based on configurable thresholds for a specific device. Organization is resolved from X-Organization header or hostname (e.g., {org}.localhost)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alerts"
                ],
                "summary": "Get alerts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "device_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Alert category (e.g., water_level)",
                        "name": "category",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD format)",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD format)",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Caution threshold value",
                        "name": "caution_threshold",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Warning threshold value",
                        "name": "warning_threshold",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Critical threshold value",
                        "name": "critical_threshold",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AlertsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/telemetry/v1/data/latest": {
            "get": {
                "description": "Retrieve the latest properties/attributes for a specific device in a space. Organization is resolved from X-Organization header or hostname (e.g., {org}.localhost)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get device properties",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "device_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space slug",
                        "name": "space_slug",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Device properties as key-value pairs",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/telemetry/v1/entities": {
            "get": {
                "description": "Retrieve a paginated list of entities with optional filtering. Organization is resolved from X-Organization header or hostname (e.g., {org}.localhost)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entities"
                ],
                "summary": "Get entities",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by entity category",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by device ID",
                        "name": "device_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by display type (comma-separated)",
                        "name": "display_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search term for filtering",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 20)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EntitiesResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/telemetry/v1/event-rules": {
            "get": {
                "description": "Retrieve all event rules with optional filtering by device. Organization is resolved from X-Organization header or hostname (e.g., {org}.localhost)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get event rules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by device ID",
                        "name": "device_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 20)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EventRulesResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new event rule for monitoring and alerting. Organization is resolved from X-Organization header or hostname (e.g., {org}.localhost)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Create event rule",
                "parameters": [
                    {
                        "description": "Event rule configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EventRuleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.EventRuleItem"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/telemetry/v1/event-rules/{rule_id}": {
            "put": {
                "description": "Update an existing event rule by ID. Organization is resolved from X-Organization header or hostname (e.g., {org}.localhost)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Update event rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event Rule ID",
                        "name": "rule_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Event rule configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EventRuleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EventRuleItem"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an event rule by ID. Organization is resolved from X-Organization header or hostname (e.g., {org}.localhost)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Delete event rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event Rule ID",
                        "name": "rule_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DeleteEventRuleResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/telemetry/v1/events/device/{device_id}": {
            "get": {
                "description": "Retrieve all events for a specific device with optional time range filtering. Organization is resolved from X-Organization header or hostname (e.g., {org}.localhost)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get events by device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "device_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of events to return (default 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Start time as Unix timestamp (milliseconds)",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "End time as Unix timestamp (milliseconds)",
                        "name": "end_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EventsByDeviceResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/telemetry/v1/geofences": {
            "get": {
                "description": "Retrieve all geofences with optional filtering by space and active status. Organization is resolved from X-Organization header or hostname (e.g., {org}.localhost)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geofences"
                ],
                "summary": "Get geofences",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by Space UUID",
                        "name": "space_id",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by active status",
                        "name": "is_active",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GeofencesListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new geofence with polygon geometry for a space. Organization is resolved from X-Organization header or hostname (e.g., {org}.localhost)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geofences"
                ],
                "summary": "Create geofence",
                "parameters": [
                    {
                        "description": "Geofence configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateGeofenceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.CreateGeofenceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/telemetry/v1/geofences/device/{device_id}": {
            "get": {
                "description": "Retrieve all geofences associated with a specific device. Organization is resolved from X-Organization header or hostname (e.g., {org}.localhost)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geofences"
                ],
                "summary": "Get geofences by device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "device_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GeofencesByDeviceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/telemetry/v1/geofences/{geofence_id}": {
            "get": {
                "description": "Retrieve a single geofence by its UUID. Organization is resolved from X-Organization header or hostname (e.g., {org}.localhost)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geofences"
                ],
                "summary": "Get geofence by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Geofence UUID",
                        "name": "geofence_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GeofenceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing geofence by ID. Organization is resolved from X-Organization header or hostname (e.g., {org}.localhost)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geofences"
                ],
                "summary": "Update geofence",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Geofence UUID",
                        "name": "geofence_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Geofence updates",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateGeofenceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateGeofenceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a geofence by ID. Organization is resolved from X-Organization header or hostname (e.g., {org}.localhost)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geofences"
                ],
                "summary": "Delete geofence",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Geofence UUID",
                        "name": "geofence_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DeleteGeofenceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/telemetry/v1/location/history": {
            "get": {
                "description": "Retrieve historical location data for a specific device within a space. Organization is resolved from X-Organization header or hostname (e.g., {org}.localhost)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Get device location history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "device_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space slug",
                        "name": "space_slug",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 format)",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 format, defaults to now)",
                        "name": "end",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of records to return (default 100, max 40320)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LocationHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/telemetry/v1/widget/data/{entity_id}": {
            "get": {
                "description": "Retrieve data for dashboard widgets based on display type (gauge, switch, chart, histogram, table, map, slider, value). Organization is resolved from X-Organization header or hostname (e.g., {org}.localhost)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "widget"
                ],
                "summary": "Get widget data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity ID",
                        "name": "entity_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Display type (gauge, switch, chart, histogram, table, map, slider, value)",
                        "name": "display_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339 format, required for chart, histogram, table)",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339 format, required for chart, histogram, table)",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Aggregation method (mean, min, max, sum, count)",
                        "name": "aggregation",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Time interval for grouping (e.g., 1m, 5m, 1h, 1d)",
                        "name": "interval",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Widget data based on display type",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AlertsResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "example": 20
                },
                "results": {
                    "type": "array",
                    "items": {}
                },
                "total_count": {
                    "type": "integer",
                    "example": 150
                }
            }
        },
        "models.CreateGeofenceRequest": {
            "type": "object",
            "required": [
                "geometry",
                "name",
                "type_zone"
            ],
            "properties": {
                "definition": {
                    "type": "object"
                },
                "geometry": {
                    "description": "Multiple polygons",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GeofenceFeature"
                    }
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "Restricted Area"
                },
                "space_id": {
                    "type": "string"
                },
                "type_zone": {
                    "description": "\"type_zone\" from frontend",
                    "type": "string",
                    "enum": [
                        "safe",
                        "danger",
                        "normal"
                    ],
                    "example": "danger"
                }
            }
        },
        "models.CreateGeofenceResponse": {
            "type": "object",
            "properties": {
                "geofence": {
                    "$ref": "#/definitions/models.GeofenceResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.DeleteEventRuleResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.DeleteGeofenceResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.EntitiesResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 25
                },
                "results": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.EventItem": {
            "type": "object",
            "properties": {
                "entity_id": {
                    "type": "string"
                },
                "event_data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "event_id": {
                    "type": "integer"
                },
                "event_level": {
                    "type": "string"
                },
                "event_type": {
                    "type": "string"
                },
                "space_slug": {
                    "type": "string"
                },
                "time_fired": {
                    "type": "string"
                }
            }
        },
        "models.EventRuleInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "definition": {
                    "type": "object"
                },
                "event_rule_id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "rule_key": {
                    "type": "string"
                }
            }
        },
        "models.EventRuleItem": {
            "type": "object",
            "properties": {
                "cooldown_sec": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "definition": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "event_rule_id": {
                    "type": "string"
                },
                "geofence_id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "repeat_able": {
                    "type": "boolean"
                },
                "rule_key": {
                    "type": "string"
                },
                "space_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.EventRuleRequest": {
            "type": "object",
            "required": [
                "rule_key"
            ],
            "properties": {
                "cooldown_sec": {
                    "type": "integer"
                },
                "definition": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "geofence_id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "repeat_able": {
                    "type": "boolean"
                },
                "rule_key": {
                    "type": "string"
                },
                "space_id": {
                    "type": "string"
                }
            }
        },
        "models.EventRulesResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "rules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.EventRuleItem"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "models.EventsByDeviceResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "device_id": {
                    "type": "string"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.EventItem"
                    }
                }
            }
        },
        "models.GeofenceFeature": {
            "type": "object",
            "properties": {
                "geometry": {
                    "type": "object"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "description": "\"Feature\"",
                    "type": "string"
                }
            }
        },
        "models.GeofenceResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "event_rule": {
                    "$ref": "#/definitions/models.EventRuleInfo"
                },
                "geofence_id": {
                    "type": "string"
                },
                "geometry": {
                    "type": "object"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "space_id": {
                    "type": "string"
                },
                "space_logo": {
                    "type": "string"
                },
                "space_name": {
                    "description": "Optional joined fields",
                    "type": "string"
                },
                "space_slug": {
                    "type": "string"
                },
                "type_zone": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.GeofencesByDeviceResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "device_id": {
                    "type": "string"
                },
                "geofences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GeofenceResponse"
                    }
                }
            }
        },
        "models.GeofencesListResponse": {
            "type": "object",
            "properties": {
                "geofences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GeofenceResponse"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "models.LocationHistoryResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 100
                },
                "locations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.LocationResponse"
                    }
                }
            }
        },
        "models.LocationResponse": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string",
                    "example": "device-123"
                },
                "latitude": {
                    "type": "number",
                    "example": 37.7749
                },
                "longitude": {
                    "type": "number",
                    "example": -122.4194
                },
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                }
            }
        },
        "models.UpdateGeofenceRequest": {
            "type": "object",
            "properties": {
                "definition": {
                    "description": "Event rule definition as JSON object",
                    "type": "object"
                },
                "geometry": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GeofenceFeature"
                    }
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "Updated Area Name"
                },
                "space_id": {
                    "type": "string"
                },
                "type_zone": {
                    "type": "string",
                    "enum": [
                        "safe",
                        "danger",
                        "normal"
                    ]
                }
            }
        },
        "models.UpdateGeofenceResponse": {
            "type": "object",
            "properties": {
                "geofence": {
                    "$ref": "#/definitions/models.GeofenceResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "API Key": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        },
        "Access Token": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "Organization slug name": {
            "type": "apiKey",
            "name": "X-Organization",
            "in": "header"
        },
        "Space slug name": {
            "type": "apiKey",
            "name": "X-Space",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Telemetry API",
	Description:      "API for telemetry service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
