// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	models "github.com/Space-DF/telemetry-service/pkgs/db/models"
)

type Factory struct {
	baseDeviceLocationMods  DeviceLocationModSlice
	baseSchemaMigrationMods SchemaMigrationModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewDeviceLocation(mods ...DeviceLocationMod) *DeviceLocationTemplate {
	return f.NewDeviceLocationWithContext(context.Background(), mods...)
}

func (f *Factory) NewDeviceLocationWithContext(ctx context.Context, mods ...DeviceLocationMod) *DeviceLocationTemplate {
	o := &DeviceLocationTemplate{f: f}

	if f != nil {
		f.baseDeviceLocationMods.Apply(ctx, o)
	}

	DeviceLocationModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingDeviceLocation(m *models.DeviceLocation) *DeviceLocationTemplate {
	o := &DeviceLocationTemplate{f: f, alreadyPersisted: true}

	o.Time = func() time.Time { return m.Time }
	o.DeviceID = func() string { return m.DeviceID }
	o.SpaceSlug = func() string { return m.SpaceSlug }
	o.Latitude = func() float64 { return m.Latitude }
	o.Longitude = func() float64 { return m.Longitude }
	o.Accuracy = func() float64 { return m.Accuracy }

	return o
}

func (f *Factory) NewSchemaMigration(mods ...SchemaMigrationMod) *SchemaMigrationTemplate {
	return f.NewSchemaMigrationWithContext(context.Background(), mods...)
}

func (f *Factory) NewSchemaMigrationWithContext(ctx context.Context, mods ...SchemaMigrationMod) *SchemaMigrationTemplate {
	o := &SchemaMigrationTemplate{f: f}

	if f != nil {
		f.baseSchemaMigrationMods.Apply(ctx, o)
	}

	SchemaMigrationModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingSchemaMigration(m *models.SchemaMigration) *SchemaMigrationTemplate {
	o := &SchemaMigrationTemplate{f: f, alreadyPersisted: true}

	o.Version = func() string { return m.Version }

	return o
}

func (f *Factory) ClearBaseDeviceLocationMods() {
	f.baseDeviceLocationMods = nil
}

func (f *Factory) AddBaseDeviceLocationMod(mods ...DeviceLocationMod) {
	f.baseDeviceLocationMods = append(f.baseDeviceLocationMods, mods...)
}

func (f *Factory) ClearBaseSchemaMigrationMods() {
	f.baseSchemaMigrationMods = nil
}

func (f *Factory) AddBaseSchemaMigrationMod(mods ...SchemaMigrationMod) {
	f.baseSchemaMigrationMods = append(f.baseSchemaMigrationMods, mods...)
}
