// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	models "github.com/Space-DF/telemetry-service/pkgs/db/models"
)

type Factory struct {
	baseDeviceLocationMods DeviceLocationModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewDeviceLocation(mods ...DeviceLocationMod) *DeviceLocationTemplate {
	return f.NewDeviceLocationWithContext(context.Background(), mods...)
}

func (f *Factory) NewDeviceLocationWithContext(ctx context.Context, mods ...DeviceLocationMod) *DeviceLocationTemplate {
	o := &DeviceLocationTemplate{f: f}

	if f != nil {
		f.baseDeviceLocationMods.Apply(ctx, o)
	}

	DeviceLocationModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingDeviceLocation(m *models.DeviceLocation) *DeviceLocationTemplate {
	o := &DeviceLocationTemplate{f: f, alreadyPersisted: true}

	o.Time = func() time.Time { return m.Time }
	o.DeviceID = func() string { return m.DeviceID }
	o.DeviceEui = func() string { return m.DeviceEui }
	o.OrganizationSlug = func() string { return m.OrganizationSlug }
	o.Latitude = func() float64 { return m.Latitude }
	o.Longitude = func() float64 { return m.Longitude }
	o.AccuracyGateways = func() int32 { return m.AccuracyGateways }

	return o
}

func (f *Factory) ClearBaseDeviceLocationMods() {
	f.baseDeviceLocationMods = nil
}

func (f *Factory) AddBaseDeviceLocationMod(mods ...DeviceLocationMod) {
	f.baseDeviceLocationMods = append(f.baseDeviceLocationMods, mods...)
}
