// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "github.com/Space-DF/telemetry-service/pkgs/db/models"
	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type DeviceLocationMod interface {
	Apply(context.Context, *DeviceLocationTemplate)
}

type DeviceLocationModFunc func(context.Context, *DeviceLocationTemplate)

func (f DeviceLocationModFunc) Apply(ctx context.Context, n *DeviceLocationTemplate) {
	f(ctx, n)
}

type DeviceLocationModSlice []DeviceLocationMod

func (mods DeviceLocationModSlice) Apply(ctx context.Context, n *DeviceLocationTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// DeviceLocationTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type DeviceLocationTemplate struct {
	Time      func() time.Time
	DeviceID  func() string
	SpaceSlug func() string
	Latitude  func() float64
	Longitude func() float64
	Accuracy  func() float64

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the DeviceLocationTemplate
func (o *DeviceLocationTemplate) Apply(ctx context.Context, mods ...DeviceLocationMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.DeviceLocation
// according to the relationships in the template. Nothing is inserted into the db
func (t DeviceLocationTemplate) setModelRels(o *models.DeviceLocation) {}

// BuildSetter returns an *models.DeviceLocationSetter
// this does nothing with the relationship templates
func (o DeviceLocationTemplate) BuildSetter() *models.DeviceLocationSetter {
	m := &models.DeviceLocationSetter{}

	if o.Time != nil {
		val := o.Time()
		m.Time = omit.From(val)
	}
	if o.DeviceID != nil {
		val := o.DeviceID()
		m.DeviceID = omit.From(val)
	}
	if o.SpaceSlug != nil {
		val := o.SpaceSlug()
		m.SpaceSlug = omit.From(val)
	}
	if o.Latitude != nil {
		val := o.Latitude()
		m.Latitude = omit.From(val)
	}
	if o.Longitude != nil {
		val := o.Longitude()
		m.Longitude = omit.From(val)
	}
	if o.Accuracy != nil {
		val := o.Accuracy()
		m.Accuracy = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.DeviceLocationSetter
// this does nothing with the relationship templates
func (o DeviceLocationTemplate) BuildManySetter(number int) []*models.DeviceLocationSetter {
	m := make([]*models.DeviceLocationSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.DeviceLocation
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use DeviceLocationTemplate.Create
func (o DeviceLocationTemplate) Build() *models.DeviceLocation {
	m := &models.DeviceLocation{}

	if o.Time != nil {
		m.Time = o.Time()
	}
	if o.DeviceID != nil {
		m.DeviceID = o.DeviceID()
	}
	if o.SpaceSlug != nil {
		m.SpaceSlug = o.SpaceSlug()
	}
	if o.Latitude != nil {
		m.Latitude = o.Latitude()
	}
	if o.Longitude != nil {
		m.Longitude = o.Longitude()
	}
	if o.Accuracy != nil {
		m.Accuracy = o.Accuracy()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.DeviceLocationSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use DeviceLocationTemplate.CreateMany
func (o DeviceLocationTemplate) BuildMany(number int) models.DeviceLocationSlice {
	m := make(models.DeviceLocationSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableDeviceLocation(m *models.DeviceLocationSetter) {
	if !(m.Time.IsValue()) {
		val := random_time_Time(nil)
		m.Time = omit.From(val)
	}
	if !(m.DeviceID.IsValue()) {
		val := random_string(nil, "255")
		m.DeviceID = omit.From(val)
	}
	if !(m.SpaceSlug.IsValue()) {
		val := random_string(nil, "255")
		m.SpaceSlug = omit.From(val)
	}
	if !(m.Latitude.IsValue()) {
		val := random_float64(nil)
		m.Latitude = omit.From(val)
	}
	if !(m.Longitude.IsValue()) {
		val := random_float64(nil)
		m.Longitude = omit.From(val)
	}
	if !(m.Accuracy.IsValue()) {
		val := random_float64(nil)
		m.Accuracy = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.DeviceLocation
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *DeviceLocationTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.DeviceLocation) error {
	var err error

	return err
}

// Create builds a deviceLocation and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *DeviceLocationTemplate) Create(ctx context.Context, exec bob.Executor) (*models.DeviceLocation, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableDeviceLocation(opt)

	m, err := models.DeviceLocations.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a deviceLocation and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *DeviceLocationTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.DeviceLocation {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a deviceLocation and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *DeviceLocationTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.DeviceLocation {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple deviceLocations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o DeviceLocationTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.DeviceLocationSlice, error) {
	var err error
	m := make(models.DeviceLocationSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple deviceLocations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o DeviceLocationTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.DeviceLocationSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple deviceLocations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o DeviceLocationTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.DeviceLocationSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// DeviceLocation has methods that act as mods for the DeviceLocationTemplate
var DeviceLocationMods deviceLocationMods

type deviceLocationMods struct{}

func (m deviceLocationMods) RandomizeAllColumns(f *faker.Faker) DeviceLocationMod {
	return DeviceLocationModSlice{
		DeviceLocationMods.RandomTime(f),
		DeviceLocationMods.RandomDeviceID(f),
		DeviceLocationMods.RandomSpaceSlug(f),
		DeviceLocationMods.RandomLatitude(f),
		DeviceLocationMods.RandomLongitude(f),
		DeviceLocationMods.RandomAccuracy(f),
	}
}

// Set the model columns to this value
func (m deviceLocationMods) Time(val time.Time) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.Time = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m deviceLocationMods) TimeFunc(f func() time.Time) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.Time = f
	})
}

// Clear any values for the column
func (m deviceLocationMods) UnsetTime() DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.Time = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m deviceLocationMods) RandomTime(f *faker.Faker) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.Time = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m deviceLocationMods) DeviceID(val string) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.DeviceID = func() string { return val }
	})
}

// Set the Column from the function
func (m deviceLocationMods) DeviceIDFunc(f func() string) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.DeviceID = f
	})
}

// Clear any values for the column
func (m deviceLocationMods) UnsetDeviceID() DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.DeviceID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m deviceLocationMods) RandomDeviceID(f *faker.Faker) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.DeviceID = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m deviceLocationMods) SpaceSlug(val string) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.SpaceSlug = func() string { return val }
	})
}

// Set the Column from the function
func (m deviceLocationMods) SpaceSlugFunc(f func() string) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.SpaceSlug = f
	})
}

// Clear any values for the column
func (m deviceLocationMods) UnsetSpaceSlug() DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.SpaceSlug = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m deviceLocationMods) RandomSpaceSlug(f *faker.Faker) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.SpaceSlug = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m deviceLocationMods) Latitude(val float64) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.Latitude = func() float64 { return val }
	})
}

// Set the Column from the function
func (m deviceLocationMods) LatitudeFunc(f func() float64) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.Latitude = f
	})
}

// Clear any values for the column
func (m deviceLocationMods) UnsetLatitude() DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.Latitude = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m deviceLocationMods) RandomLatitude(f *faker.Faker) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.Latitude = func() float64 {
			return random_float64(f)
		}
	})
}

// Set the model columns to this value
func (m deviceLocationMods) Longitude(val float64) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.Longitude = func() float64 { return val }
	})
}

// Set the Column from the function
func (m deviceLocationMods) LongitudeFunc(f func() float64) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.Longitude = f
	})
}

// Clear any values for the column
func (m deviceLocationMods) UnsetLongitude() DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.Longitude = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m deviceLocationMods) RandomLongitude(f *faker.Faker) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.Longitude = func() float64 {
			return random_float64(f)
		}
	})
}

// Set the model columns to this value
func (m deviceLocationMods) Accuracy(val float64) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.Accuracy = func() float64 { return val }
	})
}

// Set the Column from the function
func (m deviceLocationMods) AccuracyFunc(f func() float64) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.Accuracy = f
	})
}

// Clear any values for the column
func (m deviceLocationMods) UnsetAccuracy() DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.Accuracy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m deviceLocationMods) RandomAccuracy(f *faker.Faker) DeviceLocationMod {
	return DeviceLocationModFunc(func(_ context.Context, o *DeviceLocationTemplate) {
		o.Accuracy = func() float64 {
			return random_float64(f)
		}
	})
}

func (m deviceLocationMods) WithParentsCascading() DeviceLocationMod {
	return DeviceLocationModFunc(func(ctx context.Context, o *DeviceLocationTemplate) {
		if isDone, _ := deviceLocationWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = deviceLocationWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
